version: '3.7'
services:
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: ./.postgres_env
    environment:
      POSTGRES_USER: zauth
volumes:
  pgdata:
